analyzy/prepare_stats.py
analyzy/histogram.py
analyzy/plot_min_mode_avg.py
analyzy/entropizace_cen.py
analyzy/plot_cenovy_odstup_a.py
analyzy/plot_cenovy_odstup_b.py
analyzy/plot_index_sladeni.py
analyzy/plot_sladenost.py
analyzy/scatterplot_sladenost_cenovy_odstup_b.py
analyzy/prepareOutput.js
reports/reporter.js
