analyzy/prepare_stats.py
analyzy/histogram.py
analyzy/souladnost_cenovych_odstupu.py
analyzy/plot_min_mode_avg.py
analyzy/entropizace_cen.py
analyzy/plot_cenovy_odstup_b.py
analyzy/plot_brand_index_sladeni.py
analyzy/plot_index_sladeni.py
analyzy/plot_sladenost.py
analyzy/scatterplot_sladenost_cenovy_odstup_b.py
analyzy/regression_iP_Np.py
analyzy/scatterplot_nP_iB.py
analyzy/prepareOutput.js
analyzy/export_to_csv.py
reports/requestReports.cjs
reports/reporter.js
reports/docx2pdf.sh
